# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0045_auto_20170204_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gears_aquired',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='match',
            name='trigger_hopper',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='auto_trigger_hopper',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
