# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0046_auto_20170204_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gears_scored',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
