# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0047_match_gears_scored'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Defense',
        ),
    ]
