# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0050_match_gears_picked_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='high_efficiency_load',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='high_efficiency_load', to='scoutingapp.HighEfficiency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='hopper_load',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hopper_load', to='scoutingapp.HopperLoad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='low_efficiency_load',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='low_efficiency_load', to='scoutingapp.HighEfficiency'),
            preserve_default=False,
        ),
    ]
