# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0055_auto_20170212_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volley',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(max_length=100)),
                ('accuracy', models.CharField(max_length=100)),
                ('ball_count', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='high_efficiency_load',
        ),
        migrations.RemoveField(
            model_name='match',
            name='hopper_load',
        ),
        migrations.RemoveField(
            model_name='match',
            name='low_efficiency_load',
        ),
        migrations.AddField(
            model_name='volley',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.Match'),
        ),
    ]
