# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0100_auto_20180217_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cubeacquired',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cubescored',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cubewhen',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
