language: python
python:
        - "3.4"


install:
        - pip3 install .
        - pip3 install -r requirements.txt

after_script:
        - codeclimate-test-reporter

script: coverage run --source='.' wsgi/manage.py test scoutingapp
