language: python
python:
        - "3.4"


install:
        - pip3 install .
        - pip3 install -r requirements.txt

after_script:
        - codeclimate-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

script: coverage run --source='.' manage.py test scoutingapp
