# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0044_auto_20170204_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='auto_dropped_ball',
        ),
        migrations.RemoveField(
            model_name='match',
            name='auto_high_goal',
        ),
        migrations.RemoveField(
            model_name='match',
            name='auto_high_goal_2',
        ),
        migrations.AddField(
            model_name='match',
            name='auto_low_efficiency_load',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.HighEfficiency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='auto_high_efficiency_load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_high_efficiency_load', to='scoutingapp.HighEfficiency'),
        ),
    ]
