# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 02:36
from __future__ import unicode_literals

from django.db import migrations, models

def create_default_rows(apps, schema_editor):
	CubeAcquired = apps.get_model("scoutingapp", "CubeAcquired")
	pre = CubeAcquired.objects.get_or_create(name='Pre-Acquired')[0] # get_or_create auto-saves
	ground = CubeAcquired.objects.get_or_create(name='Ground')[0]
	exch = CubeAcquired.objects.get_or_create(name='Exchange')[0]
	Portal = CubeAcquired.objects.get_or_create(name='Portal')[0]

	CubeScored = apps.get_model("scoutingapp", "CubeScored")
	exch = CubeScored.objects.get_or_create(name ='Exchange')[0]
	scale = CubeScored.objects.get_or_create(name ='Scale')[0]
	own_switch = CubeScored.objects.get_or_create(name ='Own Switch')[0]
	enemy_switch = CubeScored.objects.get_or_create(name ='Opponet Switch')[0]
	dropped = CubeScored.objects.get_or_create(name ='Dropped')[0]

	When = apps.get_model("scoutingapp", 'CubeWhen')
	teleop = When.objects.get_or_create(name="Teleop")[0]
	Auto = When.objects.get_or_create(name="Auto")[0]


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0099_auto_20180217_0232'),
    ]

    operations = [
	migrations.RunPython(create_default_rows)
    ]
