# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-17 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('first_name', models.CharField(default=b'', max_length=100, null=True)),
                ('last_name', models.CharField(default=b'', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AllianceMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('scouter_number', models.DecimalField(decimal_places=0, max_digits=1)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.Alliance')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='CubeAcquired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CubePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.CubeAcquired')),
            ],
        ),
        migrations.CreateModel(
            name='CubeScored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CubeWhen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetailUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=b'', max_length=100, null=True)),
                ('last_name', models.CharField(default=b'', max_length=100, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name=b'email address')),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EndGameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_number', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
                ('auto_move_yn', models.BooleanField(default=False, verbose_name=b'Auto Move')),
                ('duplicate', models.DecimalField(decimal_places=0, max_digits=100, null=True)),
                ('robot_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Robot1card', to='scoutingapp.Card')),
                ('robot_end_game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='robot1endgame', to='scoutingapp.EndGameState')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='PreloadedGearAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_number', models.DecimalField(decimal_places=0, default=0, max_digits=5, primary_key=True, serialize=False)),
                ('team_name', models.CharField(default=b'UNNAMED', max_length=200)),
                ('team_color', models.CharField(max_length=7, null=True)),
            ],
            options={
                'ordering': ('team_number',),
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'UNAMED', max_length=200)),
                ('event_code', models.CharField(default=b'UNAMED', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CredentialsModel',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('credential', oauth2client.contrib.django_util.models.CredentialsField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='currently_in_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoutingapp.Tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='scouted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='scouted_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoutingapp.Tournament'),
        ),
        migrations.AddField(
            model_name='cubeplace',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.Match'),
        ),
        migrations.AddField(
            model_name='cubeplace',
            name='scored',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.CubeScored'),
        ),
        migrations.AddField(
            model_name='cubeplace',
            name='when',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.CubeWhen'),
        ),
        migrations.AddField(
            model_name='alliancematch',
            name='robot_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilot1card', to='scoutingapp.Card'),
        ),
        migrations.AddField(
            model_name='alliancematch',
            name='scouted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alliancematch',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoutingapp.Tournament'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoutingapp.Team'),
        ),
    ]
