# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0002_initialrows_20180217_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='cubeplace',
            name='scouted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
