# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-10 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0003_cubeplace_scouted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.DecimalField(decimal_places=0, max_digits=3)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.Tournament')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.Team')),
            ],
        ),
    ]
