# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0040_auto_20170204_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopperLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='auto_trigger_hopper',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='match',
            name='auto_hopper_load',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.HopperLoad'),
        ),
    ]
