# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-04 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0042_auto_20170204_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='HopperEfficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HopperLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='auto_efficiency_load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.HopperEfficiency'),
        ),
        migrations.AlterField(
            model_name='match',
            name='auto_hopper_load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.HopperLoad'),
        ),
    ]
