# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0048_delete_defense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='defense2_crossed',
        ),
        migrations.RemoveField(
            model_name='match',
            name='defense3_crossed',
        ),
        migrations.RemoveField(
            model_name='match',
            name='defense4_crossed',
        ),
        migrations.RemoveField(
            model_name='match',
            name='defense5_crossed',
        ),
        migrations.RemoveField(
            model_name='match',
            name='dropped_boulders',
        ),
        migrations.RemoveField(
            model_name='match',
            name='fed_boulder',
        ),
        migrations.RemoveField(
            model_name='match',
            name='low_bar_crossed',
        ),
        migrations.RemoveField(
            model_name='match',
            name='low_goals_scored',
        ),
    ]
