# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0049_auto_20170208_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='gears_picked_up',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
