# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoutingapp', '0098_detailuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CubeAcquired',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CubePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.CubeAcquired')),
            ],
        ),
        migrations.CreateModel(
            name='CubeScored',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CubeWhen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='HighEfficiency',
        ),
        migrations.DeleteModel(
            name='HopperLoad',
        ),
        migrations.RemoveField(
            model_name='alliancematch',
            name='auto_pilot_gears_acquired',
        ),
        migrations.RemoveField(
            model_name='alliancematch',
            name='auto_pilot_rotors_engaged',
        ),
        migrations.RemoveField(
            model_name='alliancematch',
            name='fails_to_spin_rotors',
        ),
        migrations.RemoveField(
            model_name='alliancematch',
            name='forgot_reserve_gear',
        ),
        migrations.RemoveField(
            model_name='alliancematch',
            name='pilot_gears_acquired',
        ),
        migrations.RemoveField(
            model_name='alliancematch',
            name='pilot_rope_deploy_time',
        ),
        migrations.RemoveField(
            model_name='alliancematch',
            name='pilot_rotors_engaged',
        ),
        migrations.RemoveField(
            model_name='alliancematch',
            name='pilot_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='auto_gears_scored',
        ),
        migrations.RemoveField(
            model_name='match',
            name='auto_hopper_triggered',
        ),
        migrations.RemoveField(
            model_name='match',
            name='gears_dropped',
        ),
        migrations.RemoveField(
            model_name='match',
            name='gears_scored',
        ),
        migrations.RemoveField(
            model_name='match',
            name='gears_type',
        ),
        migrations.RemoveField(
            model_name='match',
            name='preloaded_gear_action',
        ),
        migrations.RemoveField(
            model_name='match',
            name='teleop_hoppers_triggered',
        ),
        migrations.DeleteModel(
            name='GearAction',
        ),
        migrations.DeleteModel(
            name='RopeType',
        ),
        migrations.AddField(
            model_name='cubeplace',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.Match'),
        ),
        migrations.AddField(
            model_name='cubeplace',
            name='scored',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.CubeScored'),
        ),
        migrations.AddField(
            model_name='cubeplace',
            name='when',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutingapp.CubeWhen'),
        ),
    ]
